### ISSUE TITLE
footer wrap-around

### ISSUE THREAD

**Issue by philibin** [icambron/timestack#6]
I am having a problem when I try to have an event that is an entire day or even 21 hours.

The footer (where it shows from midnight through the following midnight) wraps the last time onto the next line.  But it doesn't do it consistently. for example if you change the end time on line 175 from 

end: '2012-08-26T17:59',

to

end: '2012-08-26T18:59',

you will see that 17:59 wraps 5:00 PM to the next line but 18:59 has both 5:00 PM and 6:00 PM on the same line. It starts wrapping again at 21:59 and puts 9:00 PM on the next line.

here is the fiddle: https://jsfiddle.net/4mexzyat/

Thank you,
-Bill

**Comment by icambron** [comment]
So that doesn't look like it's the latest version. I spotted the issue and when I went to modify the code, I saw the fix was already there. [Here's the commit where I did it](https://github.com/icambron/timestack/commit/db0e583a544219f41da02f9d599fa29a1eaddbe9). Specifically, the version you have computes the width of each cell like this:

```js
width = (100 / dates.length).toFixed(2) + "%";
```

which breaks because of rounding issues. The current code does this:

```js
width = (100 / dates.length - 0.01).toFixed(3) + "%";
```

specifically to fix this problem. So you should be able to grab the latest from [here](https://raw.githubusercontent.com/icambron/timestack/master/files/timestack.js) and be all set.

LMK if that doesn't work and I'll reopen. I pasted the JS into your fiddle and it seems to work, though. See here: https://jsfiddle.net/4mexzyat/1/
